const ALLOWED_MEME_IMAGE_ORIGINS = new Set([
  "https://i.imgflip.com",
  "https://imgflip.com",
  "https://media1.giphy.com",
  "https://media3.giphy.com",
]);

export const memeData = Object.freeze([
  { word: "DOGE", image: "https://i.imgflip.com/4t0m5.jpg" },
  { word: "CHAD", image: "https://i.imgflip.com/35bdwf.jpg" },
  { word: "STONKS", image: "https://i.imgflip.com/3388rw.png" },
  { word: "ALIENS", image: "https://imgflip.com/s/meme/Ancient-Aliens.jpg" },
  { word: "ROLL-SAFE", image: "https://i.imgflip.com/1h7in3.jpg" },
  { word: "FINE", image: "https://i.imgflip.com/1if1k1.jpg" },
  { word: "DAMN", image: "https://i.imgflip.com/tc08x.jpg" },
  { word: "JUAN", image: "https://i.imgflip.com/4jg4me.jpg" },
  { word: "GREEN", image: "https://i.imgflip.com/8i9nai.png" },
  { word: "BLACKBEARD", image: "https://i.imgflip.com/8o96jr.png" },
  { word: "PEAK", image: "https://i.imgflip.com/ajqaov.png" },
  { word: "FREE", image: "https://i.imgflip.com/8v1jx7.jpg" },
  { word: "THINK", image: "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExN2g1OWY5djkydXgzMjU3dzA4ajkxbGdwYzBtcWdjenVlNG1nNmxtMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CncEX02H3bxf6NjbK4/giphy.gif" },
  { word: "RAGEBAIT", image: "https://i.imgflip.com/9mjcoy.jpg" },
  { word: "BRAINROT", image: "https://i.imgflip.com/9p82jm.jpg" },
  { word: "SKIBIDI", image: "https://i.imgflip.com/7mzkd0.jpg" },
  { word: "AMOGUS", image: "https://i.imgflip.com/525km4.png" },
  { word: "NICHE", image: "https://i.imgflip.com/aduxgk.jpg" },
  { word: "CINEMA", image: "https://i.imgflip.com/8d317n.png" },
  { word: "LISTEN", image: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDE0cnZqeWNuZ3AwY2M2YW1qY3B3bGE1eG1paXI3dDQ2OGJnazY1aCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HB0lWJK35iy6U0bBRj/giphy.gif" },
  { word: "SUNSHINE", image: "https://i.imgflip.com/8ke1ej.jpg" },
  { word: "KNOW", image: "https://i.imgflip.com/95y76p.png" },
  { word: "JARVIS", image: "https://i.imgflip.com/9ejgym.jpg" },
  { word: "NYAN", image: "https://i.imgflip.com/atevl.jpg" },
  { word: "DABABY", image: "https://i.imgflip.com/53jvnk.jpg" },
  { word: "HANDSHAKE", image: "https://imgflip.com/s/meme/Epic-Handshake.jpg" },
  { word: "PHILOSORAPTOR", image: "https://imgflip.com/s/meme/Philosoraptor.jpg" },
  { word: "TRADE", image: "https://i.imgflip.com/54hjww.jpg" },
  { word: "MERCY", image: "https://i.imgflip.com/3p5foq.jpg" },
  { word: "DOAKES", image: "https://i.imgflip.com/9r1yow.jpg" },
  { word: "SYMPHONY", image: "https://i.imgflip.com/91i10d.png" },
  { word: "WOJAK", image: "https://i.imgflip.com/x0vjs.jpg" },
  { word: "ANKHA", image: "https://i.imgflip.com/5mt6el.jpg" },
  { word: "WEDNESDAY", image: "https://i.imgflip.com/1xf1u4.jpg" },
  { word: "HUTCHERSON", image: "https://i.imgflip.com/86tjoo.jpg" },
  { word: "PADORU", image: "https://i.imgflip.com/3sl706.png" },
  { word: "COOK", image: "https://i.imgflip.com/74bvex.png" },
  { word: "SADGE", image: "https://i.imgflip.com/4hgx7z.jpg" },
  { word: "MONKE", image: "https://i.imgflip.com/3b79fb.jpg" },
  { word: "BROTHER", image: "https://i.imgflip.com/2r6y59.jpg" },
  { word: "JEFF", image: "https://i.imgflip.com/y6wrw.jpg" },
  { word: "SKYRIM", image: "https://i.imgflip.com/2s0mqs.png" },
  { word: "FLOPPA", image: "https://i.imgflip.com/47jccz.jpg" },
  { word: "SOYJAK", image: "https://i.imgflip.com/5cik8d.png" },
  { word: "GABEN", image: "https://i.imgflip.com/6iees.jpg" },
  { word: "CHEEMS", image: "https://i.imgflip.com/3nzkub.png" },
  { word: "SCIENCE", image: "https://i.imgflip.com/xm49.jpg" },
  { word: "ALPHA", image: "https://i.imgflip.com/89tqzj.jpg" },
  { word: "JERMA", image: "https://i.imgflip.com/4w3yao.jpg" },
  { word: "COPIUM", image: "https://i.imgflip.com/4h8d1x.png" },
  { word: "RIPBOZO", image: "https://i.imgflip.com/64vr26.png" },
  { word: "CORTISOL", image: "https://i.imgflip.com/am7lfp.png" },
  { word: "VAGUE", image: "https://i.imgflip.com/aiupnj.png" },
  { word: "CRINE", image: "https://i.imgflip.com/ab70ks.png" },
  { word: "PIBBLE", image: "https://i.imgflip.com/a9yyor.png" },
  { word: "SDIYBT", image: "https://i.imgflip.com/a2dvas.png" },
  { word: "SKEBOB", image: "https://i.imgflip.com/9zu8is.png" },
  { word: "UPSCALE", image: "https://i.imgflip.com/9xvbb7.png" },
  { word: "SYBAU", image: "https://i.imgflip.com/a0wyzz.jpg" },
  { word: "RIGBY", image: "https://i.imgflip.com/9zq7c7.png" },
  { word: "AIRBALL", image: "https://i.imgflip.com/9g6kg5.png" },
  { word: "MARCUS", image: "https://i.imgflip.com/a3gnue.jpg" },
  { word: "MEOWL", image: "https://i.imgflip.com/a52z8j.jpg" },
  { word: "SEASALT", image: "https://i.imgflip.com/9q0mkk.jpg" },
  { word: "TECHNOLOGIA", image: "https://i.imgflip.com/9x11p5.png" },
  { word: "LARRY", image: "https://imgflip.com/s/meme/Larry-The-Cable-Guy.jpg" },
  { word: "PEARTO", image: "https://i.imgflip.com/9eyb4y.jpg" },
  { word: "JAKING", image: "https://i.imgflip.com/9l31vu.png" },
  { word: "COOKED", image: "https://i.imgflip.com/9iasb2.png" },
  { word: "CHILL", image: "https://i.imgflip.com/9au02y.jpg" },
  { word: "SHAYLA", image: "https://i.imgflip.com/9mqp0v.jpg" },
  { word: "HYPERPIGMENTATION", image: "https://i.imgflip.com/9hv1ey.png" },
  { word: "SHAQ", image: "https://i.imgflip.com/9710jq.png" },
  { word: "RIZZLER", image: "https://i.imgflip.com/98ridl.jpg" },
  { word: "FREAKBOB", image: "https://i.imgflip.com/8vdcyp.jpg" },
  { word: "MEWING", image: "https://i.imgflip.com/8q11dg.png" },
  { word: "AMBASING", image: "https://i.imgflip.com/736pg8.jpg" },
  { word: "TROLL", image: "https://imgflip.com/s/meme/Troll-Face.jpg" },
  { word: "DIABEETUS", image: "https://i.imgflip.com/svcml.jpg" },
  { word: "STAREDAD", image: "https://i.imgflip.com/tcj1d.jpg" },
  { word: "KONAMI", image: "https://i.imgflip.com/1id6o5.jpg" },
  { word: "BADGER", image: "https://i.imgflip.com/3dgtk7.jpg" },
  { word: "LOSS", image: "https://i.imgflip.com/2126xr.jpg" },
  { word: "DREAM", image: "https://i.imgflip.com/6vj61b.jpg" },
  { word: "YARANAIKA", image: "https://i.imgflip.com/1yx0ik.jpg" },
  { word: "SISYPHUS", image: "https://i.imgflip.com/37tjkj.jpg" },
  { word: "YAMCHA", image: "https://i.imgflip.com/pqu7y.jpg" },
  { word: "NOPE", image: "https://i.imgflip.com/4zkn5r.png" },
  { word: "GTFO", image: "https://i.imgflip.com/146dl.jpg" },
  { word: "PANIK", image: "https://i.imgflip.com/45dvxy.png" },
  { word: "QWOP", image: "https://i.imgflip.com/wvs91.jpg" },
  { word: "BRIAN", image: "https://imgflip.com/s/meme/Bad-Luck-Brian.jpg" },
  { word: "CHUNGUS", image: "https://i.imgflip.com/2ptq1i.png" },
  { word: "PEPE", image: "https://i.imgflip.com/lntct.jpg" },
  { word: "KAPPA", image: "https://i.imgflip.com/r7583.jpg" },
  { word: "HAROLD", image: "https://i.imgflip.com/1cf8by.jpg" },
  { word: "DANK", image: "https://i.imgflip.com/k5h8q.jpg" },
  { word: "KEKW", image: "https://i.imgflip.com/3qiu6h.jpg" },
  { word: "PEPEGA", image: "https://i.imgflip.com/31o20n.png" },
  { word: "SPONGEGAR", image: "https://imgflip.com/s/meme/Spongegar.jpg" },
  { word: "COMMUNITY", image: "https://i.imgflip.com/3w94cq.png" },
  { word: "HOUSE", image: "https://i.imgflip.com/x48n0.jpg" },
  { word: "MEGAMIND", image: "https://i.imgflip.com/64slsz.png" },
  { word: "PENNYWISE", image: "https://i.imgflip.com/1n657s.jpg" },
  { word: "CUPHEAD", image: "https://i.imgflip.com/3j3gvd.png" },
  { word: "JOEY", image: "https://i.imgflip.com/3u3gv3.jpg" },
  { word: "VECTORED", image: "https://i.imgflip.com/3j6mhv.png" },
  { word: "MASLOW", image: "https://i.imgflip.com/4c1ksn.jpg" },
  { word: "CLIPPY", image: "https://i.imgflip.com/4c1ksn.jpg" },
  { word: "KHABY", image: "https://i.imgflip.com/5axusj.png" },
  { word: "DONKEY", image: "https://i.imgflip.com/6d2du4.png" },
  { word: "NARCOS", image: "https://i.imgflip.com/1ubch3.jpg" },
  { word: "NAPOLEON", image: "https://i.imgflip.com/82jfen.png" },
  { word: "ROLWET", image: "https://i.imgflip.com/2vw2hw.jpg" },
  { word: "HACKER", image: "https://i.imgflip.com/2zte8w.png" },
  { word: "DOWNFALL", image: "https://i.imgflip.com/8tsxeu.png" },
  { word: "GHOST", image: "https://i.imgflip.com/71t1ia.png" },
  { word: "COOMER", image: "https://i.imgflip.com/4vms6e.png" },
  { word: "KRONK", image: "https://i.imgflip.com/60qb3t.jpg" },
  { word: "LINUS", image: "https://i.imgflip.com/3i73e0.jpg" },
  { word: "BIBBLE", image: "https://i.imgflip.com/2l299s.jpg" },
  { word: "EXODIA", image: "https://i.imgflip.com/43wukd.png" },
  { word: "KIRBY", image: "https://i.imgflip.com/378j9d.jpg" },
  { word: "VEGETA", image: "https://i.imgflip.com/7ok8yi.png" },
  { word: "BLINKING", image: "https://i.imgflip.com/1k2spq.jpg" },
  { word: "AWKWARD", image: "https://i.imgflip.com/t590k.jpg" },
  { word: "CHAEYOUNG", image: "https://i.imgflip.com/2z7icw.jpg" },
  { word: "CICLO", image: "https://i.imgflip.com/57taf3.jpg" },
  { word: "APPROVED", image: "https://i.imgflip.com/409vuc.jpg" },
  { word: "BULLY", image: "https://i.imgflip.com/50pkmo.png" },
  { word: "BONK", image: "https://i.imgflip.com/3xc256.png" },
  { word: "BONEYARD", image: "https://i.imgflip.com/3vhsml.jpg" },
  { word: "WADUH", image: "https://i.imgflip.com/7hczt0.jpg" },
  { word: "GAVIN", image: "https://i.imgflip.com/1qso3n.jpg" },
  { word: "EDGY", image: "https://i.imgflip.com/6ktvnp.jpg" },
  { word: "KAKYOIN", image: "https://i.imgflip.com/3m1gla.jpg" },
  { word: "WOMEN", image: "https://i.imgflip.com/78mxrc.png" },
  { word: "OBJECTION", image: "https://i.imgflip.com/4oiw8j.jpg" },
  { word: "TROMPET", image: "https://i.imgflip.com/4b5f4i.png" },
  { word: "CHOCOLATE", image: "https://i.imgflip.com/wjbma.jpg" },
  { word: "SHINJI", image: "https://i.imgflip.com/6gc97h.jpg" },
  { word: "STARMAN", image: "https://i.imgflip.com/8n91ax.jpg" },
]);

export const getSafeMemeImageUrl = (image) => {
  try {
    const url = new URL(image);
    if (url.protocol !== "https:" || !ALLOWED_MEME_IMAGE_ORIGINS.has(url.origin)) {
      return "";
    }
    return url.href;
  } catch {
    return "";
  }
};

export const getRandomMeme = () => {
  const randomIndex = Math.floor(Math.random() * memeData.length);
  return memeData[randomIndex];
};
